# Site Configuration
site:
  title: "Dmytro Momot - Engineering Leader & Software Architect"
  description: "Personal website of Dmytro Momot, an engineering leader with expertise in distributed systems and team leadership."
  author: "Dmytro Momot"
  email: "mail+website@dmomot.com"
  rel_path: "/"

# Social Links
social:
  github: "https://github.com/dmitrymomot"
  linkedin: "https://www.linkedin.com/in/dmitrymomot"
  twitter: "https://twitter.com/dmitry_momot"

# Header Content
header:
  title:
    - "Empowering Teams"
    - "Scaling Systems"
    - "Driving Innovation"
  description: "I'm Dmytro, a technology leader who transforms engineering teams and complex systems into high-performing assets. With 15+ years of experience, I help companies scale their tech operations and drive innovation."
  cta:
    - label: "Contact Me"
      url: "mailto:mail@dmomot.com"
      icon: "mail"
    - label: "Schedule a Call"
      url: "https://calendly.com/dmitrymomot"
      icon: "calendar"

# Services Section
services:
  title: "You Can Ask Me For"
  items:
    - title: "Technical Interview"
      description: "Conduct thorough technical assessments to identify top talent for your engineering team."
      icon: "users" # This refers to the Feather icon name

    - title: "Technology Consulting"
      description: "Provide expert advice on technology stack selection, best practices, and strategic technical decisions."
      icon: "cloud"

    - title: "Architecture Design"
      description: "Design scalable and robust system architectures that can handle complex requirements and high traffic loads."
      icon: "layout"

    - title: "Technical Leadership"
      description: "Guide and mentor engineering teams to deliver high-quality software solutions and foster a culture of innovation."
      icon: "edit"

# Projects Section
projects:
  title: "Featured Projects"
  profile_link: "https://www.linkedin.com/in/dmitrymomot"
  items:
    - title: "PIN-UP.TECH"
      url: "https://pin-up.tech"
      description: "Led engineering team through monolith to microservices transformation, significantly improving system stability and reliability."
      tags:
        - "Team Leadership"
        - "Monolith to Microservices"
        - "Reliability"

    - title: "Sator Platform"
      url: "https://sator.io"
      description: "Built and launched a Web3 entertainment platform, leading a team of 15 engineers."
      tags:
        - "Web3"
        - "Product Launch"
        - "Team Building"

    - title: "Stafferly ATS"
      url: "https://stafferly.io"
      description: "Co-founded and developed an applicant tracking system to automate recruitment processes."
      tags:
        - "Startup"
        - "ATS"
        - "Co-Founder"

    - title: "Washé Mobile App"
      url: "https://washe.io"
      description: "Architected and scaled an on-demand car wash system with native mobile apps, analytics dashboard, and distributed backend infrastructure."
      tags:
        - "Mobile"
        - "System Design"
        - "Architecture"

# Technical Expertise Section
expertise:
  title: "Technical Expertise"
  categories:
    - title: "Leadership & Management"
      icon: "users"
      skills:
        - "Engineering Team Leadership"
        - "Technical Team Building"
        - "Hiring & Talent Development"
        - "Mentoring & Coaching"

    - title: "System Architecture"
      icon: "layout"
      skills:
        - "Distributed Systems Design"
        - "Microservices Architecture"
        - "Event Sourcing & CQRS"
        - "High-Load Applications"

    - title: "Backend Development"
      icon: "code"
      skills:
        - "Golang (Primary Language)"
        - "API Design & Development"
        - "Event-Driven Systems"
        - "gRPC & JSON-RPC"

    - title: "Frontend & Mobile"
      icon: "monitor"
      skills:
        - "React & Next.js"
        - "Vue.js & Nuxt.js"
        - "Svelte & SvelteKit"
        - "Flutter Development"

    - title: "Infrastructure & DevOps"
      icon: "server"
      skills:
        - "Docker & Kubernetes"
        - "CI/CD Automation"
        - "DigitalOcean Cloud"
        - "Infrastructure as Code"

    - title: "Data & Communication"
      icon: "database"
      skills:
        - "PostgreSQL & MySQL"
        - "MongoDB & Redis"
        - "NATS Messaging"
        - "WebSocket Solutions"

# Footer Configuration
footer:
  copyright: "© 2024 Dmytro Momot"
  license:
    text: "Personal Website"
    url: "https://github.com/dmitrymomot/dmitrymomot.github.io"
    license_type: "CC BY-NC-ND 4.0"
    license_url: "https://creativecommons.org/licenses/by-nc-nd/4.0"
