baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Dmitry Momot"
theme                   = "sam"
# pygmentsStyle           = "native"                     # https://help.farbox.com/pygments.html
# pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    uglyurls            = true
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/favicon.ico"
    homepage            = "main"
    galleryFolder       = "images/"
    clickablePhotos     = true
    footerText          = "Powered by Hugo. Theme by Vicki Lai. Hosted on GitHub."
    copyright           = "2018 © Dmitry Momot."
# Metadata
    description         = "Personal site of Dmitry Momot."
    # twitterCard         = "summary_large_image"
    # primaryImage        = "/logo.png"

[[params.mainMenu]]
    link = "/about"
    text = "whois"

[[params.mainMenu]]
    link = "/posts"
    text = "notes"

[[params.mainMenu]]
    link = "https://www.linkedin.com/in/dmitrymomot/"
    text = "linkedin"

[[params.mainMenu]]
    link = "https://github.com/dmitrymomot"
    text = "github"
